#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=20gb,walltime=1:00:00
#PBS -N app-connectivity-assignments-to-wmc

mkdir -p wmc wmc/tracts wmc/surfaces

# convert to wmc
if [ ! -f ./wmc/classification.mat ]; then
	time singularity exec -e docker://brainlife/pyafq:0.4.1 ./wmc-generation.py
fi

# create surfaces for visualizer
if [ ! -f ./wmc/surfaces/index.json ]; then
	echo "Generating surfaces/ vtk from aparc+aseg.mgz"
	time singularity exec -e docker://brainlife/pythonvtk:1.1 ./parcellation2vtks.py
fi

if [ -f ./wmc/classification.mat ]; then
	echo "complete"
	exit 0
else
	echo "failed"
	exit 1
fi
